"""empty message

Revision ID: 3b81116932c9
Revises: 27f7b39a82c8
Create Date: 2014-04-17 09:58:04.163506

"""

# revision identifiers, used by Alembic.
revision = '3b81116932c9'
down_revision = '27f7b39a82c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
